### PR TITLE
Update version to pass build metadata with "+" separator

### PR DESCRIPTION
**Pull request by jewzaam**
https://semver.org/#spec-item-10

We hit a problem with a prior version of this operator (https://github.com/openshift/dedicated-admin-operator/commit/0159209) where the first 7 chars of git hash were numeric and had a leading zero (0).  This is not allowed per https://semver.org/#spec-item-9

See https://jira.coreos.com/browse/SREP-1811

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/hold

So this change looks fine, but will it break CSV generation going backwards if the image tag format is changing? Placing a hold to answer this question. If it won't break anything, then feel free to `/hold cancel`

**Comment by jewzaam** [comment]
@cblecker csv generation uses the package file in the catalog source to determine the current version, it doesn't regenerate it.  You can verify with `make build-catalog-image` and check the file generated in `bundles-staging/`

**Comment by jewzaam** [comment]
Happy to keep the hold until you remove it, another set of eyes to confirm what I'm seeing is good if it might break upgrades.

**Comment by jewzaam** [comment]
/hold cancel
Will review what happens in stage wrt breaking upgrade. Based on what I see in the generation of the catalogsource it'll be fine.

**Pull request merged**
