### PR TITLE
Unified Dockerfile in build/Dockerfile and updated README

### PR DESCRIPTION
**Pull request by rogbas**
Dockerfile moved from build/ci-operator/ to build/.
Build process and README updated.

### CODE REVIEW

**Comment by jewzaam** [comment]
We break ci if we just change it here.  Clean steps are:

1. copy `build/ci-operator/Dockerfile` to `build/Dockerfile`
2. update openshift/release to reference `build/Dockerfile`
3. delete `build/ci-operator/Dockerfile`

**Comment by lisa** [comment]
/lgtm

dang bot :)

**Pull request merged**
